### ISSUE TITLE
Issue with rendering ads

### ISSUE THREAD

**Issue by ix-certification** [indexexchange/just-premium-adapter#4]
Hello,

We've been testing your adapter using test placement ID 34364.  Test ads successfully rendered, however the test ad in the winning bid renders outside the wining slot (ie, the ad renders at the bottom of the page regardless of where the winning slot is located on the page).

Is this expected behaviour?  Does this raise any concerns regarding the functionality of the adapter within our wrapper?

**Comment by mkalafior** [comment]
Hi @ix-certification ,

This is expected behaviour and generally how we operate. So no worries. 

Of course, if you concern, publisher is fully aware of this.
